### ISSUE TITLE
Improve SEO Description assignment.

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/hugo-component-tnd-seo#1]
@budparr  I think we agree that SEO description should be inherited as follow:

.1 `.Summary`
.2 `.Params.description`
.3 `.Params.SEO.description`

☝️ But I think that when using `.Params.description`, we should limit the char length as for FreshEBT, when they fill this field, they don't have SEO in mind. What do you think?

**Comment by budparr** [comment]
Not so sure about limiting char length. Is there a hard requirement from the social networks on this?

**Comment by regisphilibert** [comment]
No the social networks, but the description meta, I think it's good practice to keep it short.

**Comment by budparr** [comment]
But I think that could have unintended results. I think it's a matter of educating (or really labeling fields), rather than creating arbitrary cutoffs. Editors have the option to override with the SEO field and they should.

**Comment by regisphilibert** [comment]
We gained speed use if/else instead of overwriting the variable multiple time! Only tested on AALDEF yet, but will broaden testing tomorrow.

I'll make sure data is still sound after this though!

**Comment by budparr** [comment]
fantastic!
